"""empty message

Revision ID: 85a7bb8978eb
Revises: e6f5decced63
Create Date: 2022-03-07 23:10:27.228160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a7bb8978eb'
down_revision = 'e6f5decced63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mass', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hair_color', sa.String(length=80), nullable=True),
    sa.Column('skin_color', sa.String(length=80), nullable=True),
    sa.Column('eye_color', sa.String(length=80), nullable=True),
    sa.Column('birth_year', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('homeworld', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('person')
    op.add_column('planet', sa.Column('url', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'planet', 'item', ['id'], ['id'])
    op.drop_column('planet', 'name')
    op.drop_column('planet', 'edited')
    op.drop_column('planet', 'created')
    op.drop_column('user', 'is_active')
    op.add_column('vehicle', sa.Column('url', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'vehicle', 'item', ['id'], ['id'])
    op.drop_column('vehicle', 'name')
    op.drop_column('vehicle', 'edited')
    op.drop_column('vehicle', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('created', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('edited', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.drop_column('vehicle', 'url')
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('planet', sa.Column('created', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('planet', sa.Column('edited', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('planet', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'url')
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('height', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('mass', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('hair_color', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('skin_color', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('eye_color', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('birth_year', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('created', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('edited', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('homeworld', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.drop_table('character')
    op.drop_table('item')
    # ### end Alembic commands ###
