"""empty message

Revision ID: d4d9566cc9ee
Revises: 85a7bb8978eb
Create Date: 2022-03-07 23:16:46.504209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d9566cc9ee'
down_revision = '85a7bb8978eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'population')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('population', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
